Option -h added to lpjsubmit, -v and -l to configure.sh

diff --git a/bin/lpjsubmit_slurm b/bin/lpjsubmit_slurm
--- a/bin/lpjsubmit_slurm
+++ b/bin/lpjsubmit_slurm
@@ -6,7 +6,7 @@
 ##    sh script to generate and submit parallel SLURM jobs using               ##
 ##    Intel MPI.                                                               ##
 ##                                                                             ##
-##    Usage: lpjsubmit [-class c] [-group g] [-wtime time] [-blocking n]       ##
+##    Usage: lpjsubmit [-h] [-class c] [-group g] [-wtime time] [-blocking n]  ##
 ##                     [-o output] [-e error] [-q] [-nocheck] [-norun]         ##
 ##                     [-constraint c] [-option a=b] ntask [LPJargs...]        ##
 ##                                                                             ##
@@ -18,7 +18,7 @@
 ##                                                                             ##
 #################################################################################
 
-USAGE="Usage: $0 [-class c] [-group g] [-wtime time] [-blocking n] [-o output] [-e error] [-q] [-nocheck] [-norun] [-dependency id] [-couple program] [-constraint c] [[-option a=b] ...] ntasks [args ...]"
+USAGE="Usage: lpjsubmit [-class c] [-group g] [-wtime time] [-blocking n] [-o output] [-e error]\n[-q] [-nocheck] [-norun] [-dependency id] [-couple program] [-constraint c] [[-option a=b] ...] ntasks [args ...]"
 
 if [ "$LPJROOT" = "" ]
 then
@@ -41,11 +41,37 @@ options=""
 
 while(( "$#" )); do
   case "$1" in
+    -h|--help)
+      echo -e "lpjsubmit - Submit parallel SLURM job for LPJmL simulations\n"
+      echo -e $USAGE
+      echo -e "\nArguments"
+      echo "-h,--help      print this help text"
+      echo "-class c       set SLURM class, default is 'short'"
+      echo "-group g       set SLURM group"
+      echo "-wtime time    set wall clock limit of job. Time must be in the format hh:mm:ss"
+      echo "-blocking n    set blocking (number of tasks per node), default is unlimited"
+      echo "-o output      set filename of output file"
+      echo "-e error       set filename of error file"
+      echo "-q,--quiet     only error messages are displayed, other output is suppressed"
+
+      echo "-nocheck       do not check input files and output directories"
+
+      echo "-norun         do not submit job to batch queue, creates slurm.jcf file only"
+      echo "-dependency id job will be scheduled after job with job id id finished successfully"
+
+      echo "-constraint c  define constraint c for SLURM job"
+      echo "-option op=txt set option op to txt for SLURM job. This option can be repeated multiple times"
+      echo "-couple prg    start couple prg in the background before starting LPJmL"
+      echo "ntasks         number of MPI tasks"
+      echo "args           arguments and options of lpjml"
+      echo -e "\n(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file"
+      exit 0
+      ;;
     -class)
     if [ $# -lt 2 ]
     then
       echo >&2 Error: class missing
-      echo >&2 $USAGE
+      echo -e >&2 $USAGE
       exit 1
     fi
     shift 1
@@ -56,7 +82,7 @@ while(( "$#" )); do
       if [ $# -lt 2 ]
       then
         echo >&2 Error: group missing
-        echo >&2 $USAGE
+        echo -e >&2 $USAGE
         exit 1
       fi
       shift 1
@@ -67,7 +93,7 @@ while(( "$#" )); do
       if [ $# -lt 2 ]
       then
         echo >&2 Error: wall clock time missing
-        echo >&2 $USAGE
+        echo -e >&2 $USAGE
         exit 1
       fi
       shift 1
@@ -78,7 +104,7 @@ while(( "$#" )); do
       if [ $# -lt 2 ]
       then
         echo >&2 Error: blocking factor missing
-        echo >&2 $USAGE
+        echo -e >&2 $USAGE
         exit 1
       fi
       shift 1
@@ -89,7 +115,7 @@ while(( "$#" )); do
      if [ $# -lt 2 ]
      then
        echo >&2 Error: output filename missing
-       echo >&2 $USAGE
+       echo -e >&2 $USAGE
        exit 1
      fi
      shift 1
@@ -100,14 +126,14 @@ while(( "$#" )); do
      if [ $# -lt 2 ]
      then
        echo >&2 Error: error filename  missing
-       echo >&2 $USAGE
+       echo -e >&2 $USAGE
        exit 1
      fi
      shift 1
      error=$1
      shift 1
      ;;
-   -q)
+   -q|--quiet)
      shift 1
      quiet="-Q"
      ;;
@@ -115,7 +141,7 @@ while(( "$#" )); do
      if [ $# -lt 2 ]
      then
        echo >&2 Error: jobid missing
-       echo >&2 $USAGE
+       echo -e >&2 $USAGE
        exit 1
      fi
      shift 1
@@ -126,7 +152,7 @@ while(( "$#" )); do
      if [ $# -lt 2 ]
      then
        echo >&2 Error: program name missing
-       echo >&2 $USAGE
+       echo -e >&2 $USAGE
        exit 1
      fi
      shift 1
@@ -137,7 +163,7 @@ while(( "$#" )); do
      if [ $# -lt 2 ]
      then
        echo >&2 Error: constraint missing
-       echo >&2 $USAGE
+       echo -e >&2 $USAGE
        exit 1
      fi
      shift 1
@@ -148,7 +174,7 @@ while(( "$#" )); do
      if [ $# -lt 2 ]
      then
        echo >&2 Error: option missing
-       echo >&2 $USAGE
+       echo -e >&2 $USAGE
        exit 1
      fi
      shift 1
@@ -165,7 +191,7 @@ while(( "$#" )); do
      ;;
    -*)
      echo >&2 Invalid option $1
-     echo >&2 $USAGE
+     echo -e >&2 $USAGE
      exit 1
      ;;
    *)
@@ -177,7 +203,7 @@ done
 if [ $# -lt 1 ]
 then
   echo >&2 Error: Number of tasks missing
-  echo >&2 $USAGE
+  echo -e >&2 $USAGE
   exit 1
 fi
 
@@ -254,7 +280,7 @@ then
   echo >>slurm.jcf
 fi
 cat <<EOF >>slurm.jcf
-srun --propagate  \$LPJROOT/bin/lpjml $args
+srun \$LPJROOT/bin/lpjml $args
 
 rc=\$?  # save return code of srun
 exit \$rc # exit with return code
